### ISSUE TITLE
Make the client send its version when calling the server

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/diracx#258]
The server should given an error if the client version is too old

The minimum version should be configured in the pyproject as a metadata such that the extension can overwrite it (`diracx.min_client_version`)

**Comment by chrisburr** [comment]
* `diracx-client/src/diracx/client/_patch.py`
* `diracx-client/src/diracx/client/aio/_patch.py`
* https://fastapi.tiangolo.com/tutorial/middleware/?h=middle
* `diracx-routers/pyproject.toml`

```toml
[project.entry-points."diracx.min_client_version"]
diracx = 1.2.3
lhcbdirac = 
```
