### ISSUE TITLE
Document migration from Dirac v8 to Dirac V9 + diracx

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/diracx#331]
This migration will be painful but a one off. Current order of things:

* deploy Dirac v9 on the server with a Dirac v8 client
* deploy diracx 
* make sure the CS syncs 
* deploy Dirac v9 clients

**Comment by natthan-pigoux** [comment]
Deploy DiracX on an existing cluster:
- verify if the cluster has a cluster issuer:
` kubectl get clusterissuer`
if yes disable `cert-manager`.
- verify if there is a ingress-controller installed:
`kubectl get ingressClass -A`
if yes use the specify ingress class.
- external access:
  - if it is manage by an external-dns service: annotate the ingress configuration:
  ```
  ingress:
    [...]
    annotations:
        # # Specific hostname used for external access
        external-dns.alpha.kubernetes.io/hostname: <hostname>
        external-dns.alpha.kubernetes.io/target: <static_ip>
      # # Specific IP used for external access
      loadBalancerIP: <static_ip>
  ```
- Encountered Issues: 
    - external-dns: several IPs can be associated to the choosen hostname. The admin must delete them by hand in the external-dns service conf to the wanted IP.
    - rabbit-mq: `ERROR ==> Couldn't start RabbitMQ in background.`
    ```
        - rabbitmq:
      podSecurityContext:
        enabled: true
      containerSecurityContext:
        enabled: true
    ```
    - IAM client configuration: the client must be configured in once and not being modified afterward otherwise it can lead to strange issue. If the clientn is misconfigured it must be recreated.
